version = "1.0.0"

# External information - observable by other agents
[external]
# Required: Character archetype or name
archetype = ""

# Required: Core definition of who/what the character is (10-1000 characters)
description = ""

# Required: How the character speaks and interacts (10-500 characters)
communication_style = ""

# Required: Strengths, virtues, appealing qualities (minimum 1)
# Can use multiline strings for detailed descriptions:
# positive_traits = [
#   "organized",
#   """highly analytical - tends to break down complex problems
#   into manageable pieces"""
# ]
positive_traits = []

# Required: Flaws, vices, challenging qualities (minimum 1)
negative_traits = []

# Optional: Special abilities, knowledge, expertise
unique_skills = []

# Internal information - private to this agent only
[internal]
# Optional: Detailed history and context (max 2000 characters)
background = ""

# Required: How the character makes choices (10-500 characters)
decision_style = ""

# Optional: Hidden information, undisclosed facts, concealed traits
# This can include both hidden personality traits and factual secrets:
# secrets = [
#   "planning to quit next month",
#   "secretly judgmental of less organized people"
# ]
secrets = []
